basePath: /
definitions:
  dto.Error:
    properties:
      message:
        type: string
    type: object
host: localhost:8080
info:
  contact:
    email: acardoso.ti@gmail.com
    name: Augusto Cardoso dos Santos
    url: https://github.com/aleroxac
  description: Segundo desafio do treinamento GoExpert(FullCycle)
  license:
    name: Full Cycle License
    url: https://fullcycle.com.br
  termsOfService: http://swagger.io/terms
  title: goexpert-fatest-zipcode-api
  version: 1.0.0
paths:
  /cep/{cep}:
    get:
      consumes:
      - application/json
      description: Get CEP
      parameters:
      - description: cep address
        in: path
        name: cep
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: object
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dto.Error'
      summary: Get CEP
      tags:
      - cep
swagger: "2.0"
